name: Build and Test on macOS

on:
  push:
    branches: [ main ]
    path: 
      - 'src/**'
      - '.github/workflows/ci-xmake-macos.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/ci-xmake-macos.yml'

jobs:
  macosbuild:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.2

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: v2.8.2
          actions-cache-folder: '.xmake-cache'

      - name: xmake repo --update
        run: xmake repo --update

      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
            ${{ runner.workspace }}/build/.build_cache

      - name: build
        run: xmake build --yes -vD

      - name: test
        run: xmake run --yes -vD